version: '2'
services:
  web:
    container_name: thegirlcode-backend
    environment:
      PORT: 65344
      NODE_ENV: production
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - '65344:65344'
    links:
      - mongo
  mongo:
    container_name: thegirlcode-mongo
    image: mongo
    volumes:
      - ./.mongo:/data/db
    ports:
      - '27017:27017'
